# Generated by Django 4.1.2 on 2022-12-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
