# Generated by Django 4.1.2 on 2023-01-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employees_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employee_pics_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
