# Generated by Django 4.1.2 on 2023-01-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_delete_employee_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_name', models.CharField(max_length=40)),
            ],
        ),
    ]
