# Generated by Django 4.1.2 on 2023-01-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_project_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project_manager',
        ),
    ]
