# Generated by Django 4.0.4 on 2022-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=30)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=50)),
                ('emp_phone_no', models.BigIntegerField()),
                ('emp_doj', models.DateField()),
                ('emp_dob', models.DateField()),
                ('emp_job_title', models.CharField(max_length=20)),
                ('emp_address', models.TextField()),
            ],
        ),
    ]
