# Generated by Django 4.1.2 on 2022-12-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_attendance_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='time_out',
        ),
    ]
