# Generated by Django 4.1.2 on 2022-12-14 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_attendance_timed_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='timed_out',
            new_name='is_timed_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
