# Generated by Django 4.1.2 on 2022-12-19 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_rename_timed_out_attendance_is_timed_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
