# Generated by Django 4.1.2 on 2023-01-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_delete_project_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
