# Generated by Django 4.1.2 on 2023-01-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_pics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee_pics',
        ),
    ]
